### PR TITLE
Fix build that has broken from a protobuf update

### PR DESCRIPTION
**Pull request by scopej**
The database.Ancestry protobuf has changed format and now contains a database.AncestryLayer instead of a database.Layer.

### CODE REVIEW

**Comment by scopej** [comment]
This is a fix for https://github.com/optiopay/klar/issues/136

**Comment by hashmap** [comment]
Thanks for the pr! I found it also requires updating `vendor`. After that I see `clair/clair_test.go:131:14: undefined: clairpb.AncestryLayer`

**Comment by scopej** [comment]
Thanks! Sorry I missed that.

**Comment by hashmap** [comment]
Thanks for your contribution!

**Pull request merged**
